const fs = require('fs');
const path = require('path');

const DOMAIN = 'https://jimmy-j-xy.github.io/auto-podcaster';
const EPISODES_DIR = path.join(__dirname, 'episodes');
const OUTPUT_FILE = path.join(__dirname, 'feed.xml');

const PODCAST_INFO = {
    title: "Jimmy's Tech Daily (吉米科技早报)",
    description: "Daily updates on China tech, trends, and business. Generated by AI. (每日中国科技与商业动态，AI自动生成)",
    author: "Jimmy Ventures",
    email: "jimmy@example.com",
    image: "https://via.placeholder.com/1400x1400.png?text=Jimmy+Tech", // 以后换个好看的封面
    language: "zh-cn"
};

function generateRSS() {
    const files = fs.readdirSync(EPISODES_DIR).filter(f => f.endsWith('.mp3'));
    
    // 按时间倒序（新的在前面，这里假设文件名越大越新，或者你可以读取文件创建时间）
    files.sort().reverse(); 

    let itemsXML = '';

    files.forEach(file => {
        const filePath = path.join(EPISODES_DIR, file);
        const stats = fs.statSync(filePath);
        const url = `${DOMAIN}/episodes/${file}`;
        const date = new Date(stats.mtime).toUTCString();
        
        // 简单处理：提取文件名作为标题
        const title = file.replace('.mp3', '').replace(/_/g, ' ').toUpperCase();

        itemsXML += `
        <item>
            <title>${title}</title>
            <description>Auto-generated episode: ${title}</description>
            <enclosure url="${url}" length="${stats.size}" type="audio/mpeg"/>
            <guid>${url}</guid>
            <pubDate>${date}</pubDate>
        </item>`;
    });

    const rssContent = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd">
  <channel>
    <title>${PODCAST_INFO.title}</title>
    <link>${DOMAIN}</link>
    <language>${PODCAST_INFO.language}</language>
    <copyright>&#169; ${new Date().getFullYear()} ${PODCAST_INFO.author}</copyright>
    <itunes:author>${PODCAST_INFO.author}</itunes:author>
    <itunes:summary>${PODCAST_INFO.description}</itunes:summary>
    <description>${PODCAST_INFO.description}</description>
    <itunes:owner>
      <itunes:name>${PODCAST_INFO.author}</itunes:name>
      <itunes:email>${PODCAST_INFO.email}</itunes:email>
    </itunes:owner>
    <itunes:image href="${PODCAST_INFO.image}"/>
    <itunes:category text="Technology"/>
    <itunes:explicit>no</itunes:explicit>
    ${itemsXML}
  </channel>
</rss>`;

    fs.writeFileSync(OUTPUT_FILE, rssContent);
    console.log(`RSS Feed generated at ${OUTPUT_FILE}`);
}

generateRSS();
